{
 "title": "Duck Dance Party",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Raspberry Pi 4", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Temp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"duck_bucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"temp\" and\r\n    r._field == \"temp\"\r\n    )\r\n  |> aggregateWindow(\r\n    every: duration(v: uint(v: (int(v: v.windowPeriod) * 1))),\r\n    fn: mean,\r\n    createEmpty: false\r\n  )\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"duck_bucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"cpu\" and\r\n    r._field == \"usage_idle\"\r\n    )\r\n  |> aggregateWindow(\r\n    every: duration(v: uint(v: (int(v: v.windowPeriod) * 1))),\r\n    fn: mean,\r\n    createEmpty: false\r\n  )\r\n  |> map(fn: (r) => ({ r with _value: float(v: 100) - (float(v: r._value) * float(v: 1)) }))\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"duck_bucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"disk\" and\r\n    r._field == \"used_percent\" and\r\n    (r.label == \"rootfs\" or r.label == \"bootfs\")\r\n    )\r\n  |> aggregateWindow(every: 2m, fn: mean)"
    },
    {
     "query": "from(bucket: \"duck_bucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"swap\" and\r\n    r._field == \"used_percent\" and\r\n    r.host == \"duck-orchestrator\"\r\n    )\r\n  |> aggregateWindow(every: 2m, fn: mean)\r\n  |> map(fn: (r) => ({ r with _field: \"swap\" }))"
    },
    {
     "query": "from(bucket: \"duck_bucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"mem\" and\r\n    r._field == \"used_percent\" and\r\n    r.host == \"duck-orchestrator\"\r\n    )\r\n  |> aggregateWindow(every: 2m, fn: mean)\r\n  |> map(fn: (r) => ({ r with _field: \"mem\" }))"
    }
   ]
  },
  {
   "title": "Uptime Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"duck_bucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"system\" and\r\n    r._field == \"uptime\"\r\n    )\r\n  |> aggregateWindow(\r\n    every: duration(v: uint(v: (int(v: v.windowPeriod) * 1))),\r\n    fn: mean,\r\n    createEmpty: false\r\n  )\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Ducks - System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Battery Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"duck_bucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"battery_V\"\r\n    )\r\n  |> aggregateWindow(\r\n    every: duration(v: uint(v: (int(v: v.windowPeriod) * 1))),\r\n    fn: mean,\r\n    createEmpty: false\r\n  )\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Temperature - RP2040",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"duck_bucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"temp_rp2040_C\"\r\n    )\r\n  |> aggregateWindow(\r\n    every: duration(v: uint(v: (int(v: v.windowPeriod) * 1))),\r\n    fn: mean,\r\n    createEmpty: false\r\n  )\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Ducks - Boot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Boot Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "query": "from(bucket: \"duck_bucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"boot_count\"\r\n    )"
    }
   ]
  },
  {
   "title": "Boot Reason Soft",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "query": "from(bucket: \"duck_bucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"soft_reboot_reason\"\r\n    )"
    }
   ]
  },
  {
   "title": "Boot Reason Hard",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "query": "from(bucket: \"duck_bucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"hard_reboot_reason\"\r\n    )"
    }
   ]
  },
  { "title": "Ducks - Comms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "RSSI - Pico W",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "query": "from(bucket: \"duck_bucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"rssi\"\r\n    )\r\n  |> aggregateWindow(\r\n    every: duration(v: uint(v: (int(v: v.windowPeriod) * 1))),\r\n    fn: mean,\r\n    createEmpty: false\r\n  )\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Motor RX Command Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "query": "from(bucket: \"duck_bucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"motor_cmd_rx_cnt\"\r\n    )\r\n  |> aggregateWindow(\r\n    every: duration(v: uint(v: (int(v: v.windowPeriod) * 1))),\r\n    fn: mean,\r\n    createEmpty: false\r\n  )\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "MQTT Publish Callback Error Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "query": "from(bucket: \"duck_bucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"mqtt_pub_cb_err_cnt\"\r\n    )\r\n  |> aggregateWindow(\r\n    every: duration(v: uint(v: (int(v: v.windowPeriod) * 1))),\r\n    fn: mean,\r\n    createEmpty: false\r\n  )\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "MQTT Publish Error Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "query": "from(bucket: \"duck_bucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"mqtt_pub_err_cnt\"\r\n    )\r\n  |> aggregateWindow(\r\n    every: duration(v: uint(v: (int(v: v.windowPeriod) * 1))),\r\n    fn: mean,\r\n    createEmpty: false\r\n  )\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Bad JSON Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "query": "from(bucket: \"duck_bucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"bad_json_count\"\r\n    )\r\n  |> aggregateWindow(\r\n    every: duration(v: uint(v: (int(v: v.windowPeriod) * 1))),\r\n    fn: mean,\r\n    createEmpty: false\r\n  )\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Ducks - Magnetometer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Heading",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "query": "from(bucket: \"duck_bucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"heading\"\r\n    )\r\n  |> aggregateWindow(\r\n    every: duration(v: uint(v: (int(v: v.windowPeriod) * 1))),\r\n    fn: mean,\r\n    createEmpty: false\r\n  )\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Root Mean Square Error (KASA)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "targets": [
    {
     "query": "from(bucket: \"duck_bucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"kasa_rmse\"\r\n    )\r\n  |> aggregateWindow(\r\n    every: duration(v: uint(v: (int(v: v.windowPeriod) * 1))),\r\n    fn: mean,\r\n    createEmpty: false\r\n  )\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Calibrated Mag X uT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "targets": [
    {
     "query": "from(bucket: \"duck_bucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"mag_calibrated_x_uT\"\r\n    )\r\n  |> aggregateWindow(\r\n    every: duration(v: uint(v: (int(v: v.windowPeriod) * 1))),\r\n    fn: mean,\r\n    createEmpty: false\r\n  )\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Calibrated Mag Y uT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "targets": [
    {
     "query": "from(bucket: \"duck_bucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"mag_calibrated_y_uT\"\r\n    )\r\n  |> aggregateWindow(\r\n    every: duration(v: uint(v: (int(v: v.windowPeriod) * 1))),\r\n    fn: mean,\r\n    createEmpty: false\r\n  )\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Mag X uT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "targets": [
    {
     "query": "from(bucket: \"duck_bucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"mag_x_uT\"\r\n    )\r\n  |> aggregateWindow(\r\n    every: duration(v: uint(v: (int(v: v.windowPeriod) * 1))),\r\n    fn: mean,\r\n    createEmpty: false\r\n  )\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Mag Y uT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "targets": [
    {
     "query": "from(bucket: \"duck_bucket\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"mag_y_uT\"\r\n    )\r\n  |> aggregateWindow(\r\n    every: duration(v: uint(v: (int(v: v.windowPeriod) * 1))),\r\n    fn: mean,\r\n    createEmpty: false\r\n  )\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}